// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvtVFuTxB6VdsxHglY16PUkJnn_iOpF4c',
    appId: '1:247969553719:web:a24e74d17a01a63c2a4eb2',
    messagingSenderId: '247969553719',
    projectId: 'pedidos-8693b',
    authDomain: 'pedidos-8693b.firebaseapp.com',
    storageBucket: 'pedidos-8693b.firebasestorage.app',
    measurementId: 'G-TRK5657PZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgHQ2Up3ethMKy-a_rL7KwEzy_mSVZ2Fs',
    appId: '1:247969553719:android:fa17a55098f43f5d2a4eb2',
    messagingSenderId: '247969553719',
    projectId: 'pedidos-8693b',
    storageBucket: 'pedidos-8693b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIkJzl4Pa2VhmyN5Voix-1EtvT6cC1kYY',
    appId: '1:247969553719:ios:9ad3bbfad1408d222a4eb2',
    messagingSenderId: '247969553719',
    projectId: 'pedidos-8693b',
    storageBucket: 'pedidos-8693b.firebasestorage.app',
    iosBundleId: 'com.example.pedidos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIkJzl4Pa2VhmyN5Voix-1EtvT6cC1kYY',
    appId: '1:247969553719:ios:9ad3bbfad1408d222a4eb2',
    messagingSenderId: '247969553719',
    projectId: 'pedidos-8693b',
    storageBucket: 'pedidos-8693b.firebasestorage.app',
    iosBundleId: 'com.example.pedidos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvtVFuTxB6VdsxHglY16PUkJnn_iOpF4c',
    appId: '1:247969553719:web:aefecedc3051abdc2a4eb2',
    messagingSenderId: '247969553719',
    projectId: 'pedidos-8693b',
    authDomain: 'pedidos-8693b.firebaseapp.com',
    storageBucket: 'pedidos-8693b.firebasestorage.app',
    measurementId: 'G-HZJGN4BFKS',
  );
}
